name: Test

on:
  push:
  pull_request:

jobs:
  pester:
    name: Pester
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Pester
        shell: powershell
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module Pester -RequiredVersion 3.4.0 -Scope CurrentUser -Force -SkipPublisherCheck

      - name: Run tests
        shell: powershell
        run: .\Run-Tests.ps1 -EnableExit
